// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package com.gw.stupid.consistency.entity.auto;

public final class Consistency {
  private Consistency() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WriteRequest_ExInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WriteRequest_ExInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadRequest_ExInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadRequest_ExInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021consistency.proto\"\263\001\n\014WriteRequest\022\r\n\005" +
      "group\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\022\014" +
      "\n\004type\030\004 \001(\t\022\021\n\toperation\030\005 \001(\t\022)\n\006exInf" +
      "o\030\006 \003(\0132\031.WriteRequest.ExInfoEntry\032-\n\013Ex" +
      "InfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"\203\001\n\013ReadRequest\022\r\n\005group\030\001 \001(\t\022\014\n\004data" +
      "\030\002 \001(\014\022(\n\006exInfo\030\003 \003(\0132\030.ReadRequest.ExI" +
      "nfoEntry\032-\n\013ExInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\";\n\nCpResponse\022\014\n\004data\030\001 " +
      "\001(\014\022\016\n\006errMsg\030\002 \001(\t\022\017\n\007success\030\003 \001(\010B.\n*" +
      "com.gw.stupid.consistency.entity.generat" +
      "orP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WriteRequest_descriptor,
        new java.lang.String[] { "Group", "Key", "Data", "Type", "Operation", "ExInfo", });
    internal_static_WriteRequest_ExInfoEntry_descriptor =
      internal_static_WriteRequest_descriptor.getNestedTypes().get(0);
    internal_static_WriteRequest_ExInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WriteRequest_ExInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadRequest_descriptor,
        new java.lang.String[] { "Group", "Data", "ExInfo", });
    internal_static_ReadRequest_ExInfoEntry_descriptor =
      internal_static_ReadRequest_descriptor.getNestedTypes().get(0);
    internal_static_ReadRequest_ExInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadRequest_ExInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_CpResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CpResponse_descriptor,
        new java.lang.String[] { "Data", "ErrMsg", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
