// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consistency.proto

package com.gw.stupid.consistency.entity.auto;

public interface ReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group = 1;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 1;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>map&lt;string, string&gt; exInfo = 3;</code>
   */
  int getExInfoCount();
  /**
   * <code>map&lt;string, string&gt; exInfo = 3;</code>
   */
  boolean containsExInfo(
      java.lang.String key);
  /**
   * Use {@link #getExInfoMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExInfo();
  /**
   * <code>map&lt;string, string&gt; exInfo = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExInfoMap();
  /**
   * <code>map&lt;string, string&gt; exInfo = 3;</code>
   */

  java.lang.String getExInfoOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; exInfo = 3;</code>
   */

  java.lang.String getExInfoOrThrow(
      java.lang.String key);
}
